title: Esther Farkas # your name (or website title) here
logo: "/images/logo.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Sophmore at Brooklyn College |
  Macaulay Honors College   
  <br><br>
  Computer Science Major   
  <br><br>
  <a href="https://www.linkedin.com/in/esther-farkas-b89325186/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
